{{- if and .Values.editor.keda.enabled (not .Values.editor.hpa.enabled) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-editor-keda
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: editor
    app.kubernetes.io/part-of: landing-pages
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-editor
  pollingInterval: {{ .Values.editor.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.editor.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.editor.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.editor.keda.maxReplicaCount }}
  idleReplicaCount: {{ .Values.editor.keda.idleReplicaCount }}
  triggers:
    - type: {{ .Values.editor.keda.trigger.type }}
      metadata:
{{- range $k, $v := .Values.editor.keda.trigger.metadata }}
        {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}