{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-lp
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: landing-pages
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: landing-pages
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchExpressions:
      - key: app.kubernetes.io/part-of
        operator: In
        values:
          - landing-pages
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      path: /metrics
{{- end }}