apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-web
  namespace: {{ .Values.environment.namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: {{ toJson .Values.webServices }}
  policyTypes:
    - Ingress
  ingress:
    - {}